name: example
description: "A new Flutter project."


environment:
  sdk: ^3.8.0-265.0.dev

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/dash.png
    - assets/robin.png
